version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: pgorczyca/todo-list:local
    restart: unless-stopped
    environment:
      POSTGRES_DSN: "host=postgres user=postgres password=12345 dbname=postgres port=5432 sslmode=disable"
    ports:
    - 8081:8080
    depends_on:
    - postgres
  postgres:
    image: postgres:14.2-alpine
    restart: unless-stopped
    ports:
    - 15432:5432
    environment:
      POSTGRES_PASSWORD: 12345
    volumes:
    - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: